[package]
name = "wust"
version = "0.1.0"
edition = "2024"

[dependencies]
wasmparser = "0.245"
libc = "0.2"
anyhow = "1"
wat = "1"
bilge = "0.3.0"

[dev-dependencies]
wast = "245"
wat = "1"
wasmtime = "41"

[[example]]
name = "bench_fib"

[[example]]
name = "plasma_hello"
